stages:
  - package

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
    - when: never

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: nav

docker-package:
  stage: package
  image: docker:27.4.1-cli
  services:
    - name: docker:27.4.1-dind
      command:
        - --tls=false
  before_script:
    # 需要使用支持 privileged + dind 的 Docker Runner
    - until docker info; do echo "waiting for docker daemon..."; sleep 2; done
  script:
    - docker build --build-arg PRISMA_PROVIDER=postgresql --file Dockerfile --tag "$IMAGE_NAME:$CI_COMMIT_TAG" --tag "$IMAGE_NAME:latest" .
    - docker image inspect "$IMAGE_NAME:$CI_COMMIT_TAG" --format '{{.Id}}'
    - docker save "$IMAGE_NAME:$CI_COMMIT_TAG" | gzip > "${IMAGE_NAME}-${CI_COMMIT_TAG}.tar.gz"
    - sha256sum "${IMAGE_NAME}-${CI_COMMIT_TAG}.tar.gz" > "${IMAGE_NAME}-${CI_COMMIT_TAG}.tar.gz.sha256"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG-docker-image"
    expire_in: 7 days
    paths:
      - "${IMAGE_NAME}-${CI_COMMIT_TAG}.tar.gz"
      - "${IMAGE_NAME}-${CI_COMMIT_TAG}.tar.gz.sha256"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
